### ISSUE TITLE
FAQ implies only "recommended" includes PFS

### ISSUE THREAD

**Issue by regendo** [hcrudolph/ciphersuite.info#107]
It's my understanding that you rate all cipher suites without PFS as "weak". If that's the case, both "secure" and "recommended" all support PFS.

The FAQ currently only states this for recommended, implying that cipher suites under "secure" don't guarantee it.

**Comment by hcrudolph** [comment]
Support for PFS depends on the key exchange algorithm. That is, even ciphersuites that offer less-than-optimal security guarantees may support PFS as long as their key exchange does (e.g., using DHE or ECDHE). So far, we have not called out PFS support explicitly, but we are testing this out at the moment. See https://github.com/hcrudolph/ciphersuite.info/commit/f82ed32e39b9efa6597d79d26bade6a7c9feb77d for details.

Once we roll this out into production, it should also be made more clear in the FAQ.

**Comment by hcrudolph** [comment]
ee4f7257c97bfebaa966d4d126ad231d9662927f improves the search/filter/sorting functionality and also adds the ability to sort by security rating.
