### ISSUE TITLE
Ordering options "Ascending" and "Descending" trigger opposite operations

### ISSUE THREAD

**Issue by Ricky-Tigg** [hcrudolph/ciphersuite.info#112]
Hello. The selections of _Ordering_ options _Ascending_ and _Descending_ trigger **opposite operations**. Then for example, _Ascending_ option  would have to be selected  in order to obtain a presentation **ordered by descending**, therefore from strongest to weakest in respect to theoretical security strength.

Illustration with that filters combination applied: for _Security_ select _All_, for _TLS version_ select _TLS v. 1.3_. Resulting output:

_Secure TLS_AES_128_CCM_8_SHA256
Secure TLS_AES_128_CCM_SHA256
Recommended TLS_AES_128_GCM_SHA256
Recommended TLS_AES_256_GCM_SHA384
Recommended TLS_CHACHA20_POLY1305_SHA256
Insecure TLS_SHA256_SHA256
Insecure TLS_SHA384_SHA384
Insecure TLS_SM4_CCM_SM3
Insecure TLS_SM4_GCM_SM3_

**Comment by hcrudolph** [comment]
Hi there, thanks for raising this point. The options _Ascending_ and _Descending_ simply order the ciphersuites alphabetically. They do not indicate a security ranking. Such an ordering option would be a new feature.
