### ISSUE TITLE
Non-standardised ordering of cipher suites in respect to theoretical security strength

### ISSUE THREAD

**Issue by Ricky-Tigg** [hcrudolph/ciphersuite.info#113]
Hello. It seems to me a well laudable intention within the project which is to achieve a reliable ranking of cipher suites mathematical security strengths. Nonetheless, the obvious cannot be missed, in that ordering them accordingly is giving quite trouble to developers.

Illustration by comparison with two tool suites that conform with IETF's standardization publications. Both of them by default present cipher suites in **descending** order of supposed security strength, thus **from strongest towards weakest**.

_GnuTLS_ v. 3.8.0
```
$ gnutls-cli -l --priority PFS | grep TLS1.3$
TLS_AES_256_GCM_SHA384                      0x13, 0x02	TLS1.3
TLS_CHACHA20_POLY1305_SHA256                0x13, 0x03	TLS1.3
TLS_AES_128_GCM_SHA256                      0x13, 0x01	TLS1.3
TLS_AES_128_CCM_SHA256                      0x13, 0x04	TLS1.3
```
_OpenSSL_ v. 3.1
```
$ openssl ciphers -V -s -tls1_3
0x13,0x02 - TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256   TLSv1.3 Kx=any      Au=any   Enc=CHACHA20/POLY1305(256) Mac=AEAD
0x13,0x01 - TLS_AES_128_GCM_SHA256         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(128)            Mac=AEAD
0x13,0x04 - TLS_AES_128_CCM_SHA256         TLSv1.3 Kx=any      Au=any   Enc=AESCCM(128)            Mac=AEAD
```
When it comes to this tool, a **non-standardised** ordering can be observed.

_Note_: this tool suffers an issue (!112) that is out of scope in the context of the present report; selections of _Ordering_ options _Ascending_ and _Descending_ trigger **opposite operations**.  Then as long as the issue is alive, select the _Ascending_ option in order to obtain a presentation **ordered by descending**.

For _Security_ select _All_, for _TLS version_ select _TLS v. 1.3_. Resulting output:

_Secure TLS_AES_128_CCM_8_SHA256
Secure TLS_AES_128_CCM_SHA256
Recommended TLS_AES_128_GCM_SHA256
Recommended TLS_AES_256_GCM_SHA384
Recommended TLS_CHACHA20_POLY1305_SHA256
Insecure TLS_SHA256_SHA256
Insecure TLS_SHA384_SHA384
Insecure TLS_SM4_CCM_SM3
Insecure TLS_SM4_GCM_SM3_

**Comment by hcrudolph** [comment]
Hi there, thanks for raising this point. The options _Ascending_ and _Descending_ simply order the ciphersuites alphabetically. They do not indicate a security ranking. Such an ordering option would be a new feature.
