### ISSUE TITLE
Raise content max_length in StaticPage model

### ISSUE THREAD

**Issue by hcrudolph** [hcrudolph/ciphersuite.info#18]
1000 characters turns out to be far to little space (cf. https://github.com/hcrudolph/ciphersuite.info/blob/master/directory/models.py#L193).

**Comment by ngrundmann** [comment]
Still 1000 characters

**Comment by hcrudolph** [comment]
fixed by 81d81d7ab593fcf8e406bf0a33f75027d69e1536
