### ISSUE TITLE
openapi.json shows dead link

### ISSUE THREAD

**Issue by m-terlinde** [hcrudolph/ciphersuite.info#47]
Hey guys,

https://ciphersuite.info/static/openapi.json shows two dead links.
Mentioned are: 
- "https://git.hcrudolph.com/hcrudolph/ciphersuite.info/blob/master/LICENSE"
- "https://git.hcrudolph.com/hcrudolph/ciphersuite.info"

Thanks for your work!
Matthias

**Comment by n0lz** [comment]
fixed in dev branch already. Rollout will be soon.
