### ISSUE TITLE
GCM ciphers are hard to find

### ISSUE THREAD

**Issue by m-terlinde** [hcrudolph/ciphersuite.info#49]
Hey guys,

if you just want to find all super-duper-cool GCM suites, you'll first find a bunch of CBC suites which have the disclaimer "plz use GCM instead of this padding oracle mess".

The first GCM suite is on the 5th place, the second one on 11th.

Maybe the CBC disclaimer shouldn't be searchable or so? A filtering drop down per algorithm could be useful as well.

Thanks,
Matthias

**Comment by hcrudolph** [comment]
This should be addressed as part of the improved search functionality added in ee4f7257c97bfebaa966d4d126ad231d9662927f (yet to be deployed in production as of this posting).

While no dedicated drop-down filter has been added, the improved order of search results should make it much easier to find these GCM algorithms.
