### ISSUE TITLE
Missing openssl_name value for TLS_CHACHA20_POLY1305_SHA256

### ISSUE THREAD

**Issue by MatzFan** [hcrudolph/ciphersuite.info#65]
Just started using your excellent API and noticed the above omission at https://ciphersuite.info/api/cs/TLS_CHACHA20_POLY1305_SHA256. I believe the openssl_name value ought to be the same as the IANA name key. The json given by the API is as follows:-
```json
{

    "TLS_CHACHA20_POLY1305_SHA256": {
        "gnutls_name": "",
        "openssl_name": "",
        "hex_byte_1": "0x13",
        "hex_byte_2": "0x03",
        "protocol_version": "TLS",
        "kex_algorithm": "-",
        "auth_algorithm": "-",
        "enc_algorithm": "CHACHA20 POLY1305",
        "hash_algorithm": "SHA256",
        "security": "recommended",
        "tls_version": [
            "TLS1.3"
        ]
    }

}
```
`openssl ciphers|grep TLS_CHACHA20_POLY1305_SHA256` on my machine highlights this name (openssl 1.1.1f).

I also note the 2nd hex byte seems to be incorrectly recorded [here](https://github.com/hcrudolph/ciphersuite.info/blob/959733ac42f5a1d3603bf2278eff98369ef415be/directory/fixtures/02_openssl_ciphers.yaml#L959) as `0xC3` - an OCR scan error?

**Comment by hcrudolph** [comment]
Thanks for reporting this issue! This should be fixed with the above commit, and find its way into production in the next couple of days.
