### ISSUE TITLE
Invalid signature for matrix server

### ISSUE THREAD

**Issue by rolandog** [hcrudolph/ciphersuite.info#71]
I'm not sure if this is the right place to file this.

I received the following error when trying to join through Element to [the Matrix room](https://matrix.to/#/#ciphersuiteinfo:neuland.technology):

> Invalid signature for server matrix.org with key ed25519:a_RXGa: Unable to verify signature for matrix.org: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt

This may or may not end up being a server config error:
https://github.com/matrix-org/synapse/issues/3387

**Comment by n0lz** [comment]
Can you please give some more information on the error? Do you try to create an account on our home server or do you try to join through federation? On my side everything seems to be fine

**Comment by rolandog** [comment]
Thanks for your response!

I tried to join the room through the Element client in both my mobile phone and on my laptop, so I'm thinking Federation. Sorry if I'm still a Matrix newbie, but how do I try to create an account on the Neuland server?  It was not apparent from the ciphersuites.info website.

The steps to reproduce on my laptop:
- Explore rooms
- Add new server
- Add `neuland.technology` (a green checkmark appeared and says 'looks good', but as I'm writing this post it converts to a red x and says "can't find this server or its room list")
- Room list appears:
  - Cipher Suite Info (two buttons appear: 'Preview' and 'Join')
  - Somus (no 'Preview' button appears, only 'Join')
- Clicking 'Preview'
  - Notification appears: `#ciphersuiteinfo:neuland.technology can't be previewed. Do you want to join it?`
  - Click 'Join the discussion' (see next item in list)
- Clicking 'Join'
  - Reported error message appears ('Failed to Join')
  - `Invalid signature for [...]`

Searching for both errors online (`"Invalid signature for server" "with key" "Unable to verify signature for" "<class 'nacl.exceptions.BadSignatureError'>" "Signature was forged or corrupt" "failed to make_join via any server"`) only yielded [one result](https://community.nethserver.org/t/solved-etc-pki-tls-and-subdirectories-contents/18020) (... and in the future this very thread).

Perhaps I need to create an account in the server to be able to join?

This may not necessarily be an important issue (as perhaps most of the users are , as the reason I was trying to join was to ask some questions about some listed GnuTLS cipher suites, and to point out that there may be newer up-to-date cipher suites in the new GnuTLS (#72) version than  those listed in the website.

**Comment by n0lz** [comment]
> Add neuland.technology (a green checkmark appeared and says 'looks good', but as I'm writing this post it converts to a red x and says "can't find this server or its room list")

I found a problem in the federation configuration. Fixing this requires heavy reconfiguration of the Webserver... Don't have time for this at the moment, I will try it in a few days

**Comment by ThierryBegin** [comment]
I<m having the same issue so if anyone has a solution. I tried to re-install a synapse server in docker and im unable to make it work since...

**Comment by rolandog** [comment]
Excellent!  Thank you very much for the fix.
