### ISSUE TITLE
Proposal to updated GnuTLS cipher suite availability from the manual

### ISSUE THREAD

**Issue by rolandog** [hcrudolph/ciphersuite.info#72]
I read in the ReadMe that the Cipher Suites are scraped from the [IANA TLS Cipher Suite Registry](https://www.iana.org/assignments/tls-parameters/tls-parameters.xml#tls-parameters-4), though I'm not sure if the GnuTLS availability data could be parsed from the [Supported ciphersuites](https://www.gnutls.org/manual/html_node/Supported-ciphersuites.html) appendix from the manual.

This may help automate the listing of the availability for GnuTLS specifically.

**Comment by n0lz** [comment]
We scrape IANA because they have the most complete and official list. Libraries like OpenSSL and GnuTLS don't implement all ciphers. For the search we build the names according to the naming conventions of the respective library.

**Comment by rolandog** [comment]
Thanks for your response.  That makes sense.
