### ISSUE TITLE
New cipher naming scheme and algorithms

### ISSUE THREAD

**Issue by n0lz** [hcrudolph/ciphersuite.info#73]
RFC 9189 published three new ciphers with completely different names. This results in a broken mapping for OpenSSL and GnuTLS (at the moment only in staging)

RFC 9150 messes with naming scheme too

**Comment by hcrudolph** [comment]
The parsing issue concerning these ciphers has been addressed in 6caae131445c03df2f53bbaa354254ce7799d705
